export enum SpecialEvents {
  RESIGN = "RESIGN",
  REQUEST_DRAW = "REQUEST_DRAW",
  CONFIRM_DRAW = "CONFIRM_DRAW",
  DECLINE_DRAW = "DECLINE_DRAW",
  FINISH = "FINISH",
  GAMEOVER = "GAMEOVER",
  NONE = "NONE"
}
